// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="ja">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import React from "react";
import Layout from "components/layout"
import './globals.css';

// FontAwesome for Nextjs
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss= false/* 自動個別適用を無効化 */

// render
export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="ja">
      <body>
        <Layout>
          <main>{children}</main>
        </Layout>
      </body>
    </html>
  );
}

// export const metadata = {
//   ...baseMetadata,
//   openGraph: {
//     ...openGraphMetadata,
//   },
//   twitter: {
//     ...twitterMetadata,
//   },
// };
